version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_DB: restapi_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080