bind_addr = ":8090"
log_level = "debug"
database_url_docker = "host=localhost dbname=restapi_dev sslmode=disable user=postgres password=root"
database_url = "host=localhost dbname=restapi_dev sslmode=disable"
session_key = "8EAEF25C9D3CED951024D083615C73644A119686114B8F52C16A60A9E2EB5562"